name: ci-cd for nodejs-project

on :
  push:
    branches:
      - sample
      - main
      - version

  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      environment:
        description: 'which env to deploy '
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - stage
          - production



jobs:

    setup:
      runs-on: ubuntu-latest
      outputs:
        release_version: ${{ steps.step1.outputs.release_version }}

      steps:
        - name: setting the variable
          id: step1
          run: |
            BRANCH_NAME=${GITHUB_REF_NAME}
            echo "release_version=${BRANCH_NAME}-$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT


    Nodejs-Docker-Build:

      uses: ssagarshiva/githubactions-template/.github/workflows/nodejs-dockerbuid.yml@main
      needs: [setup]
      with:
        release_version: ${{ needs.setup.outputs.release_version }}
        DOCKER_HOST: ${{ vars.DOCKER_HOST }}
        DOCKER_REPO: ${{ vars.DOCKER_REPO }}
        DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}

      secrets: inherit


    Nodejs-K8s-Deploy: 
      if: ${{ github.event_name == 'push' || github.event_inputs.environment == 'dev' }}
      uses: ssagarshiva/githubactions-template/.github/workflows/nodeks.deploy.yml@main
      needs: [setup,Nodejs-Docker-Build]
      with:
        environment: dev
        release_version: ${{ needs.setup.outputs.release_version }}
        ACR_HOST: ${{ vars.ACR_HOST }}
        ACR_USERNAME: ${{ vars.ACR_USERNAME }}
        ACR_REPO: ${{ vars.ACR_REPO }}
        AKS_CLUSTER: ${{ vars.AKS_CLUSTER }}
        AKS_RESOURCE_GROUP: ${{ vars.AKS_RESOURCE_GROUP }}
        AKS_CLUSTER_NAMESPACE: ${{ vars.AKS_CLUSTER_NAMESPACE }}
        AKS_ACR_SECRET: ${{ vars.AKS_ACR_SECRET }}

      secrets: inherit
