name: ci-cd for nodejs-project

on :
  push:
    branches:
      - sample
      - main
      - master

  workflow_dispatch: # Allows manual triggering of the workflow



jobs:

    setup:
      runs-on: ubuntu-latest
      outputs:
        release_version: ${{ steps.set-variable.outputs.repo_digests }}

      steps:
        - name: setting the variable
          id: step1
          run: |
            BRANCH_NAME=${GITHUB_REF_NAME}
            echo "release_version=${BRANCH_NAME}-$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT


    Nodejs-Docker-Build:

      uses: ssagarshiva/githubactions-template/.github/workflows/nodejs-dockerbuid.yml@main
      needs: [setup]
      with:
        release_version: ${{ needs.setup.outputs.release_version }}
        DOCKER_HOST: ${{ vars.DOCKER_HOST }}
        DOCKER_REPO: ${{ vars.DOCKER_REPO }}
        DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}

      secrets: inherit